#define FLEX_MIN_AIN0 700
#define FLEX_MAX_AIN0 1500
#define FLEX_RANGE_AIN0 (FLEX_MAX_AIN0 - FLEX_MIN_AIN0)
#define INV_FLEX_RANGE_AIN0 (1 / (double) FLEX_RANGE_AIN0)

#define FLEX_MIN_AIN2 100
#define FLEX_MAX_AIN2 1500
#define FLEX_RANGE_AIN2 (FLEX_MAX_AIN2 - FLEX_MIN_AIN2)
#define INV_FLEX_RANGE_AIN2 (1 / (double) FLEX_RANGE_AIN2)

#define FLEX_MIN_AIN4 700
#define FLEX_MAX_AIN4 1500
#define FLEX_RANGE_AIN4 (FLEX_MAX_AIN4 - FLEX_MIN_AIN4)
#define INV_FLEX_RANGE_AIN4 (1 / (double) FLEX_RANGE_AIN4)

#define FLEX_MIN_AIN6 700
#define FLEX_MAX_AIN6 1500
#define FLEX_RANGE_AIN6 (FLEX_MAX_AIN6 - FLEX_MIN_AIN6)
#define INV_FLEX_RANGE_AIN6 (1 / (double) FLEX_RANGE_AIN6)
